version: "3.8"

services:
    s1:
      image: $IMAGE
      container_name: $F_NAME
      ports: 
      - $F_PORT:$F_PORT
      command: sh -c "python3 -u -m http.server ${F_PORT} 2>> /app/data/${F_NAME}-log.txt"
      networks: 
      - l-net
      volumes:
      - data:/app/data
    s2:
      image: $IMAGE
      container_name: $S_NAME
      ports:
        - $S_PORT:$S_PORT
      command: sh -c "python3 -u -m http.server ${S_PORT} 2>> /app/data/${S_NAME}-log.txt"
      networks:
      - l-net
      volumes:
      - data:/app/data

networks:
  l-net:
    driver: bridge

volumes:
  data: 
